package com.company.enums;

public enum AdminStatus {
    CLICKED_ADD_KAFEDRA,
    ENTERED_TEACHER_NAME,
    ENTERED_TEACHER_SURNAME,
    ENTERED_TEACHER_LEVEL,
    ENTERED_TEACHER_ROOM,
    SELECT_KAFEDRA_FOR_ADD_TEACHER,
    ADD_RAHBARIYAT, ENTERED_RAHBAR_NAME, ENTERED_RAHBAR_SURNAME,
    ENTERED_RAHBAR_LEVEL, ENTERED_RAHBAR_PHONE, ENTERED_RAHBAR_ROOM,
    CLICKED_ADD_RAHBAR, SELECT_LYCEUM_IMAGE, CLICKED_ADD_BIO, SELECT_LYCEUM_MALUMOT,
    SELECT_LYCEUM_FOR_MALUMOT, SELECT_LYCEUM_FOR_VIDEO, CLICKED_ADD_VIDEO,
    SELECT_LYCEUM_VIDEO_MALUMOT, CLICKED_ADD_FOTO, SELECT_LYCEUM_FOR_FOTO, SELECT_LYCEUM_FOTO, ENTERED_TEACHER_PHONE;
}
